version: '3'
name: hrstaffportal
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_streamlit
    container_name: web
    restart: always
    ports:
      - "8501:8501"
    networks:
      - network1
    depends_on: [db]
  db:
    container_name: mariadb
    restart: always
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: RooT_#PW5532
      MARIADB_HOST: 0.0.0.0
      MARIADB_DATABASE: idcard
      MARIADB_USER: kch
      MARIADB_PASSWORD: Badge#23
    ports:
      - "3306:3306"
    networks:
      - network1
    volumes:
      - ./files/database_dump.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  network1:
    name: hrstaffportal_default
    driver: bridge
    external: false
